Administrator/urls.py
from django.urls import path
from .views import banusers, ban_user, unban_user, notallowed, event_change, event_create, event_delete

app_name = 'administrator'
urlpatterns = [
    path('banusers/', banusers, name='banusers'),
    path('ban-user/<int:user_id>/', ban_user, name='ban_user'),
    path('unban-user/<int:user_id>/', unban_user, name='unban_user'),
    path('notallowed/', notallowed, name='notallowed'),
    path('event-create/', event_create, name='event_create'),
    path('<int:parameter>/event-change/', event_change, name='event_change'),
    path('<int:parameter>/delete/', event_delete, name='even_delete'),
]

Events/urls.py
from django.urls import path
from .views import all_events, event, favourite_event

app_name = 'events'
urlpatterns = [
    path('', all_events, name='all_events'),
    path('<int:parameter>/', event, name='event'),
    path('<int:parameter>/favourite_event', favourite_event, name='favourite_event'),
]

Main/urls.py
from django.urls import path
from .views import main, about_us, contacts

app_name = 'main'
urlpatterns = [
    path('', main, name='landing'),
    path('aboutus/', about_us, name='about_us'),
    path('contacts/', contacts, name='contacts'),

]

Planetarium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_control
from django.contrib.staticfiles.views import serve
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('', include('Administrator.urls')),
    path('events/', include('Events.urls')),
    path('news/', include('News.urls')),
    path('user/', include('User.urls')),
    path('', include('Account.urls')),
    path('', include('Order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

User/urls.py
from django.urls import path
from .views import user, history, order_info, wishlist, user_change

app_name = 'user'
urlpatterns = [
    path('', user, name='profile'),
    path('change/', user_change, name='profile_change'),
    path('history/', history, name='history'),
    path('history/<int:parameter>/', order_info, name='order_info'),
    path('wishlist/', wishlist, name='wishlist')
]

Administrator/models.py
from django.db import models
from django.contrib.auth.models import User


class BanStatus(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_banned = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

Events/models.py
from django.db import models

from django.contrib.auth.models import User


class Hall(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name}"


class Event(models.Model):
    name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/events/', default="images/default.png", blank=True)
    from_date = models.DateField()
    to_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    about = models.TextField(max_length=2000)
    hall_id = models.ForeignKey(Hall, on_delete=models.CASCADE, related_name='events')
    popularity = models.PositiveSmallIntegerField()
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

    def __str__(self):
        return f"{self.name}"

Administrator/forms.py
from Events.models import Event
from django import forms


class EventForm(forms.ModelForm):
    image = forms.ImageField(required=True)

    class Meta:
        model = Event
        fields = '__all__'

    def save(self, commit=True):
        event = super().save(commit=False)
        if commit:
            event.save()
        return event

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price:
            if price < 0.0:
                raise forms.ValidationError("Ціна не може бути від'ємною!")
        elif price == 0.0:
            raise forms.ValidationError("Не може бути безкоштовного квитка!")
        return price

    def clean_popularity(self):
        popularity = self.cleaned_data.get('popularity')
        if popularity < 1 or popularity > 12:
            raise forms.ValidationError("Популярність повинна мати значення у інтервалі від 1 до 12!")
        return popularity

Administrator/views.py
from django.shortcuts import render

from Events.models import Event
from .decorators import admin_only
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.models import User

from .forms import EventForm


@admin_only
def banusers(request):
    users = User.objects.all()
    return render(request, 'banusers.html', context={'users': users})


@admin_only
def ban_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.banstatus.is_banned = True
    user.banstatus.save()
    return redirect('administrator:banusers')


@admin_only
def unban_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.banstatus.is_banned = False
    user.banstatus.save()
    return redirect('administrator:banusers')


@admin_only
def event_change(request, parameter):
    event = Event.objects.get(id=parameter)
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            form.save()
    else:
        form = EventForm(instance=event)

    return render(request, "event_form.html", {"form": form, "event": event})


@admin_only
def event_delete(request, parameter):
    event = Event.objects.get(id=parameter)
    event.delete()
    return redirect('events:all_events')


@admin_only
def event_create(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('events:all_events')
    else:
        form = EventForm()
    return render(request, 'event_form.html', {'form': form})


def notallowed(request):
    return render(request, 'notallowed.html')

Events/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Event
from django.db.models import Q
from django.core.paginator import Paginator
from Administrator.decorators import allowed_users


def all_events(request):

    search_query = request.GET.get('search', '')
    date_picker = request.GET.get('date', '')
    hall_picker = request.GET.getlist('hall', '')
    sorting = request.GET.get('sorting', '')

    if search_query is not None and search_query != ' ':
        events = Event.objects.filter(name__icontains=search_query)
    else:
        events = Event.objects.all()

    if date_picker:
        events = events.filter(from_date__lte=date_picker, to_date__gte=date_picker)

    if hall_picker:
        filters = Q()
        for parameter in hall_picker:
            filters |= Q(hall_id=parameter)
        events = events.filter(filters)

    if sorting:
        events = events.order_by(sorting)

    paginator = Paginator(events, 8)

    page_number = request.GET.get('page')
    paginator_events = paginator.get_page(page_number)
    return render(request, "all_events.html", context={'events': paginator_events})


def event(request, parameter):
    event = Event.objects.get(id=parameter)
    is_favourite = False
    if event.favourite.filter(id=request.user.id).exists():
        is_favourite = True
    return render(request, "event.html", context={'event': event, "is_favourite": is_favourite})


@allowed_users(allowed_roles=['customer'])
@login_required(login_url='account:login')
def favourite_event(request, parameter):
    event = Event.objects.get(id=parameter)
    if event.favourite.filter(id=request.user.id).exists():
        event.favourite.remove(request.user)
    else:
        event.favourite.add(request.user)
    return redirect('events:event', parameter=parameter)

Administrator/templates/banusers.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
    Користувачі
{% endblock %}

{% block content %}

{% if users %}
    <section class="links links-info-page">
        <div class="container">
            <a href="{% url 'main:landing' %}">На головну</a>
            <p>&nbsp|&nbsp</p>
            <a href="{% url 'user:profile' %}">Профіль</a>
        </div>
    </section>

    <section class="additional-info-block cart" id="cart-container">
        <div class="container">
            <h1>
                Користувачі
            </h1>
            <hr>
            <div class="block" id="cart-form">
                <div class="spacing">
                    <div class="products-params">
                        <div class="item-param item-param-name">
                            Ім'я користувача
                        </div>
                        <div class="item-param item-value-price">
                        </div>
                        <div class="item-param item-param-name">
                            Статус
                        </div>
                        <div class="item-param item-param-name">
                        </div>
                    </div>
                    <hr>
                    {% for user in users %}
                        {% if not user.is_superuser %}
                            <div class="products-params products-values">
                                <div class="item-param item-param-name">
                                        {{ user.username }}
                                </div>
                                <div class="item-param">
                                </div>
                                <div class="item-param item-param-name">
                                    {% if user.banstatus.is_banned == False %}
                                        Не заблоковано
                                    {% else %}
                                        Заблоковано
                                    {% endif %}
                                </div>
                                <div class="item-param item-param-name">
                                {% if not user.banstatus.is_banned %}
                                    <form action="/ban-user/{{ user.id }}/" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="review-order user-ban" id="ban-button">Забанити</button>
                                    </form>
                                {% else %}
                                    <form action="/unban-user/{{ user.id }}/" method="POST">
                                      {% csrf_token %}
                                        <button type="submit" class="review-order user-ban" id="unban-button">Розбанити</button>
                                    </form>
                                {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

        </div>
    </section>

{% else %}
    <div class="container">
        <h1>
            Нема користувачів
        </h1>
    </div>

{% endif %}

    <script>
        var itemCount = {{ users|length }};
        var cartForm = document.getElementById("cart-form");
        var cartContainer = document.getElementById("cart-container");
        var heightForm = 600 + (itemCount - 4) * 110;
        var heightContainer = 1100 + (itemCount - 4) * 110;
        cartForm.style.height = heightForm + "px";
        cartContainer.style.height = heightContainer + "px";
    </script>

{% endblock %}

Administrator/templates/event_change.html
{% extends 'index.html' %}

{% block title %}
    {{ event.name }}
{% endblock %}

{% block content %}


    <section class="links links-info-page">
        <div class="container">
            <a href="{% url 'main:landing' %}">На головну</a>
            <p>&nbsp|&nbsp</p>
            <a href="{% url 'events:all_events' %}">Афіша</a>
            <p class="full-name">&nbsp|&nbsp</p>
            <a class="full-name" href="{% url 'events:event' event.id %}">{{ event.name }}</a>
            <p class="short-name">&nbsp|&nbsp</p>
            <a class="short-name" href="">{{ event.short_name }}</a>
        </div>
    </section>

    <section class="poster-main-info edit-profile-page">
        <div class="container">
            {% for message in messages %}
                <h1> {{ message }}</h1>
            {% endfor %}
            <h1>
               {{ event.name }}
            </h1>
            <hr>
            {% for field_errors in form.errors.values %}
                {% for error in field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="block">
                        <img src="{{ event.image.url }}" alt="">
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <section class="posters-block posters-block-register">
                        <div class="container">
                            <div class="sub-container">
                                <div class="registration edit-profile-form change-event-form">
                                    <form name="form" method="POST" enctype="multipart/form-data">
                                        <h2>| Введіть дані |</h2>

                                            {% csrf_token %}
                                        {#    {{ form.as_p }}#}
                                        <label class="edit-parameter event-change-labels" for="id_name">Назва:</label>
                                            {{ form.name }}
                                        <label class="edit-parameter event-change-labels" for="id_short_name">Коротка назва:</label>
                                            {{ form.short_name }}
                                        <label class="edit-parameter event-change-labels" for="id_image">Постер:</label>
                                            {{ form.image }}
                                        <div class="label-input dates">
                                            <label class="edit-parameter event-change-labels" for="id_from_date">Від:</label>
                                            {{ form.from_date }}
                                        </div>
                                        <div class="label-input dates">
                                            <label class="edit-parameter event-change-labels" for="id_to_date">До:</label>
                                            {{ form.to_date }}
                                        </div>
                                        <label class="edit-parameter event-change-labels" for="id_price">Ціна:</label>
                                            {{ form.price }}
                                        <label class="edit-parameter event-change-labels" for="id_about">Опис події:</label>
                                            {{ form.about }}
                                        <label class="edit-parameter event-change-labels" for="id_hall_id">Зала:</label>
                                            {{ form.hall_id }}
                                        <div class="label-input dates">
                                            <label class="edit-parameter event-change-labels" for="id_popularity">Популярність:</label>
                                            {{ form.popularity }}
                                        </div>


                                        <button type="submit"> Змінити </button>
                                        <a class="additional-buttom" href="{% url 'events:event' event.id %}"> Повернутися </a>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </section>
                </div>
            </div>
        </div>
    </section>

    <script>
		var form_fields = document.getElementsByTagName('input')

		for (var field in form_fields){
			form_fields[field].className += 'change-input'
		}

        form_fields[4].setAttribute('type', 'date');
        form_fields[5].setAttribute('type', 'date');
        form_fields[7].className += ' about-block-change'

        var form_field_select = document.getElementsByTagName('select')[0]
        form_field_select.className += 'change-input '

        var formfield_text = document.getElementsByTagName('textarea')[0]
        formfield_text.className += 'change-input text-area-change'

    </script>

    <script>

    </script>


{#    <section class="poster-main-info">#}
{#        <div class="container">#}
{#            <div class="event-upper">#}
{#                <h1>#}
{#                    {{ event.name }}#}
{#                </h1>#}
{#            </div>#}
{#            <hr>#}
{#            <div class="row">#}
{#                <section class="posters-block posters-block-register">#}
{#                        <div class="container">#}
{#                            <div class="sub-container">#}
{#                                <div class="registration event-change">#}
{#                                    <form name="form" method="POST" enctype="multipart/form-data">#}
{#                                        <h2>| Введіть дані |</h2>#}
{##}
{#                                            {% csrf_token %}#}
                                        {#    {{ form.as_p }}#}
{##}
{#                                            {{ form.name }}#}
{#                                            {{ form.short_name }}#}
{#                                            {{ form.image }}#}
{#                                            {{ form.from_date }}#}
{#                                            {{ form.to_date }}#}
{#                                            {{ form.price }}#}
{#                                            {{ form.about }}#}
{#                                            {{ form.hall_id }}#}
{#                                            {{ form.popularity }}#}
{##}
{#                                        <button type="submit"> Змінити </button>#}
{#                                        <a class="additional-buttom" href="{% url 'events:event' event.id %}"> Повернутися </a>#}
{#                                    </form>#}
{#                                </div>#}
{#                            </div>#}
{##}
{#                        </div>#}
{#                    </section>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}




{% endblock %}

Administrator/templates/event_form.html
{% extends 'index.html' %}

{% block title %}
    {{ event.name }}
{% endblock %}

{% block content %}


    <section class="links links-info-page">
        <div class="container">
            <a href="{% url 'main:landing' %}">На головну</a>
            <p>&nbsp|&nbsp</p>
            <a href="{% url 'events:all_events' %}">Афіша</a>
            {% if event %}
                <p class="full-name">&nbsp|&nbsp</p>
                <a class="full-name" href="{% url 'events:event' event.id %}">{{ event.name }}</a>
                <p class="short-name">&nbsp|&nbsp</p>
                <a class="short-name" href="">{{ event.short_name }}</a>
            {% endif %}
        </div>
    </section>

    <section class="poster-main-info edit-profile-page">
        <div class="container">
            {% for message in messages %}
                <h1> {{ message }}</h1>
            {% endfor %}
            <h1>
                {% if event %}
                    {{ event.name }}
                {% else %}
                    Нова подія
                {% endif %}
            </h1>
            <hr>
            {% for field_errors in form.errors.values %}
                {% for error in field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="block">
                        {% if event %}
                            <img src="{{ event.image.url }}" alt="">
                        {% else %}
                            <img src="/media/images/default.png" alt="">
                        {% endif %}
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <section class="posters-block posters-block-register">
                        <div class="container">
                            <div class="sub-container">
                                <div class="registration edit-profile-form change-event-form">
                                    <form name="form" method="POST" enctype="multipart/form-data">
                                        <h2>| Введіть дані |</h2>
                                            {% csrf_token %}
                                        <label class="edit-parameter event-change-labels" for="id_name">Назва:</label>
                                            {{ form.name }}
                                        <label class="edit-parameter event-change-labels" for="id_short_name">Коротка назва:</label>
                                            {{ form.short_name }}
                                        <label class="edit-parameter event-change-labels" for="id_image">Постер:</label>
                                            {{ form.image }}
                                        <div class="label-input dates">
                                            <label class="edit-parameter event-change-labels" for="id_from_date">Від:</label>
                                            {{ form.from_date }}
                                        </div>
                                        <div class="label-input dates">
                                            <label class="edit-parameter event-change-labels" for="id_to_date">До:</label>
                                            {{ form.to_date }}
                                        </div>
                                        <label class="edit-parameter event-change-labels" for="id_price">Ціна:</label>
                                            {{ form.price }}
                                        <label class="edit-parameter event-change-labels" for="id_about">Опис події:</label>
                                            {{ form.about }}
                                        <label class="edit-parameter event-change-labels" for="id_hall_id">Зала:</label>
                                            {{ form.hall_id }}
                                        <div class="label-input dates">
                                            <label class="edit-parameter event-change-labels" for="id_popularity">Популярність:</label>
                                            {{ form.popularity }}
                                        </div>

                                        {% if event %}
                                            <button type="submit"> Змінити </button>
                                            <a class="additional-buttom" href="{% url 'events:event' event.id %}"> Повернутися </a>
                                        {% else %}
                                            <button type="submit"> Додати </button>
                                            <a class="additional-buttom" href="{% url 'events:all_events' %}"> Повернутися </a>
                                        {% endif %}


                                    </form>
                                </div>
                            </div>

                        </div>
                    </section>
                </div>
            </div>
        </div>
    </section>

    <script>
		var form_fields = document.getElementsByTagName('input')

		for (var field in form_fields){
			form_fields[field].className += 'change-input'
		}

        form_fields[4].setAttribute('type', 'date');
        form_fields[5].setAttribute('type', 'date');
        form_fields[7].className += ' about-block-change'

        var form_field_select = document.getElementsByTagName('select')[0]
        form_field_select.className += 'change-input '

        var formfield_text = document.getElementsByTagName('textarea')[0]
        formfield_text.className += 'change-input text-area-change'

    </script>

{% endblock %}

Administrator/templates/notallowed.html
{% extends 'index.html' %}

{% block title %}
    Закритий доступ
{% endblock %}

{% block content %}

    <section class="links links-info-page">
        <div class="container">
            <a href="{% url 'main:landing' %}">На головну</a>
        </div>
    </section>

    <section class="poster-main-info not-allowed">
        <div class="container">
                <h1>
                     У вас немає доступу до цієї сторінки!
                </h1>
        </div>
    </section>

{% endblock %}