Account/urls.py
from django.urls import path
from .views import register, log_in, log_out

app_name = 'account'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
]

Administrator/urls.py
from django.urls import path
from .views import banusers, ban_user, unban_user, notallowed, event_change, event_create, event_delete

app_name = 'administrator'
urlpatterns = [
    path('banusers/', banusers, name='banusers'),
    path('ban-user/<int:user_id>/', ban_user, name='ban_user'),
    path('unban-user/<int:user_id>/', unban_user, name='unban_user'),
    path('notallowed/', notallowed, name='notallowed'),
    path('event-create/', event_create, name='event_create'),
    path('<int:parameter>/event-change/', event_change, name='event_change'),
    path('<int:parameter>/delete/', event_delete, name='even_delete'),
]

Events/urls.py
from django.urls import path
from .views import all_events, event, favourite_event

app_name = 'events'
urlpatterns = [
    path('', all_events, name='all_events'),
    path('<int:parameter>/', event, name='event'),
    path('<int:parameter>/favourite_event', favourite_event, name='favourite_event'),
]

Main/urls.py
from django.urls import path
from .views import main, about_us, contacts

app_name = 'main'
urlpatterns = [
    path('', main, name='landing'),
    path('aboutus/', about_us, name='about_us'),
    path('contacts/', contacts, name='contacts'),

]

Planetarium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_control
from django.contrib.staticfiles.views import serve
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('', include('Administrator.urls')),
    path('events/', include('Events.urls')),
    path('news/', include('News.urls')),
    path('user/', include('User.urls')),
    path('', include('Account.urls')),
    path('', include('Order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

User/urls.py
from django.urls import path
from .views import user, history, order_info, wishlist, user_change

app_name = 'user'
urlpatterns = [
    path('', user, name='profile'),
    path('change/', user_change, name='profile_change'),
    path('history/', history, name='history'),
    path('history/<int:parameter>/', order_info, name='order_info'),
    path('wishlist/', wishlist, name='wishlist')
]

User/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    profile_pic = models.ImageField(upload_to='images/users/', blank=True, default="images/default_user.jpg")

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        if self.user:
            self.user.username = self.name
            self.user.save()
        super().save(*args, **kwargs)

User/forms.py
import re
from User.models import Customer
from django import forms
from django.contrib.auth.models import User


class CustomerForm(forms.ModelForm):
    delete_photo = forms.BooleanField(required=False)

    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone'].required = False

    def save(self, commit=True):
        customer = super().save(commit=False)
        if commit:
            customer.save()
            customer.user.username = customer.name
            customer.user.email = customer.email
            customer.user.save()
        return customer

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name and User.objects.filter(username=name).exists():
            if self.instance and self.instance.user.username == name:
                return name
            raise forms.ValidationError("Це ім'я вже використовується")
        return name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exists():
            if self.instance and self.instance.user.email == email:
                return email
            raise forms.ValidationError('Цей email вже використовується')
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone:
            pattern = r'^\+38\d{10}$'
            if not re.match(pattern, phone):
                raise forms.ValidationError("Телефон має бути у форматі +38 ХХХ ХХХХХХХ")
        return phone

User/views.py
from django.shortcuts import render
from Administrator.decorators import allowed_users
from Order.models import Order
from .forms import CustomerForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


@login_required(login_url='account:login')
def user(request):
    return render(request, "user.html")


@login_required(login_url='account:login')
def user_change(request):
    customer = request.user.customer
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            if form.cleaned_data['delete_photo']:
                if customer.profile_pic != 'images/default_user.jpg':
                    customer.profile_pic.delete()
                    customer.profile_pic = 'images/default_user.jpg'
            form.save()
    else:
        form = CustomerForm(instance=customer)

    return render(request, "user_change.html", {"form": form})


@login_required(login_url='account:login')
@allowed_users(allowed_roles=['customer'])
def history(request):
    customer = request.user.customer
    orders = Order.objects.filter(customer=customer)
    reversed_orders = reversed(orders)
    return render(request, "history.html", {"orders": orders, "reversed_orders": reversed_orders})


@login_required(login_url='account:login')
@allowed_users(allowed_roles=['customer'])
def order_info(request, parameter):
    order = Order.objects.get(id=parameter)
    items = order.orderitem_set.all()
    return render(request, "order_info.html", context={'order': order, 'items': items})


@login_required(login_url='account:login')
@allowed_users(allowed_roles=['customer'])
def wishlist(request):
    user = request.user
    favourite_event = user.favourite.all()
    paginator = Paginator(favourite_event, 4)

    page_number = request.GET.get('page')
    paginator_events = paginator.get_page(page_number)
    return render(request, "wishlist.html", context={'events': paginator_events})

User/templates/history.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
    {{ event.name }}
{% endblock %}

{% block content %}

{% if orders %}
    <section class="links links-info-page">
        <div class="container">
            <a href="{% url 'main:landing' %}">На головну</a>
            <p>&nbsp|&nbsp</p>
            <a href="{% url 'user:profile' %}">Профіль</a>
        </div>
    </section>

    <section class="additional-info-block cart" id="cart-container">
        <div class="container">
            <h1>
                Історія замовлень
            </h1>
            <hr>
            <div class="block" id="cart-form">
                <div class="spacing">
                    <div class="products-params">
                        <div class="item-param item-param-name">
                                Номер замовлення
                        </div>
                        <div class="item-param item-value-price">
                               Дата
                        </div>
                        <div class="item-param item-value-price">
                                Сума
                        </div>
                        <div class="item-param item-value-price"></div>
                    </div>
                    <hr>
                    {% for order in reversed_orders %}
                        {% if order.complete %}
                            <div class="products-params products-values">
                                <div class="item-param item-param-name">
                                        Замовлення №{{ order.transaction_id }}
                                </div>
                                <div class="item-param item-value-price">
                                       {{ order.date_ordered|date:"Y-m-d" }}
                                </div>
                                <div class="item-param item-value-price">
                                        {{ order.total }} грн.
                                </div>
                                <a  class="review-order" href="{% url 'user:order_info' order.id %}">Переглянути</a>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

        </div>
    </section>

{% else %}
    <div class="container">
        <h1>
            Історія порожня...
        </h1>
    </div>

{% endif %}

    <script>
        var itemCount = {{ orders|length }};
        var cartForm = document.getElementById("cart-form");
        var cartContainer = document.getElementById("cart-container");
        var heightForm = 600 + (itemCount - 4) * 110;
        var heightContainer = 1100 + (itemCount - 4) * 110;
        cartForm.style.height = heightForm + "px";
        cartContainer.style.height = heightContainer + "px";
    </script>

{% endblock %}

User/templates/order_info.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
    {{ event.name }}
{% endblock %}

{% block content %}

{% if items %}
    <section class="links links-info-page">
        <div class="container">
            <a href="{% url 'main:landing' %}">На головну</a>
            <p>&nbsp|&nbsp</p>
            <a href="{% url 'user:profile' %}">Профіль</a>
            <p>&nbsp|&nbsp</p>
            <a href="{% url 'user:history' %}">Історія</a>
        </div>
    </section>

    <section class="additional-info-block cart" id="cart-container">
        <div class="container">
            <h1 class="history-order-h">
                Замовлення №{{ order.transaction_id }}
            </h1>
            <hr>

            <div class="block" id="cart-form">
                <div class="spacing">
                    <div class="products-params">
                        <div class="item-param delete-item">
                        </div>
                        <div class="item-param">
                        </div>
                        <div class="item-param item-param-name">
                                Назва
                        </div>
                        <div class="item-param item-value-price">
                                Дата
                        </div>
                        <div class="item-param item-value-price">
                                Ціна
                        </div>
                        <div class="item-param">
                                Кількість
                        </div>
                        <div class="item-param item-value-price">
                                Сумарно
                        </div>
                    </div>
                    <hr>
                        {% for item in items %}
                        <div class="products-params products-values">
                            <div class="item-param delete-item">

                            </div>
                            <div class="item-param">
                                <img src="{{ item.event.image.url }}" alt="">
                            </div>
                            <div class="item-param item-param-name">
                                    <a class="order-event" href="{% url 'events:event' item.event.id %}">{{ item.event.name }}</a>
                            </div>
                            <div class="item-param item-value-price">
                                     {{ item.date_event|date:"Y-m-d" }}
                            </div>
                            <div class="item-param item-value-price">
                                    {{ item.event.price }} грн.
                            </div>
                            <div class="item-param">
                                    {{ item.quantity }}
                            </div>

                            <div class="item-param item-value-price">
                                    {{ item.get_total }} грн.
                            </div>
                        </div>
                        {% endfor %}
                </div>
            </div>

        </div>
    </section>

{% else %}
    <div class="container">
        <h1>
            Упс помилка...
        </h1>
    </div>

{% endif %}

    <script>
        var itemCount = {{ items|length }};
        var cartForm = document.getElementById("cart-form");
        var cartContainer = document.getElementById("cart-container");
        var heightForm = 600 + (itemCount - 4) * 110;
        var heightContainer = 1100 + (itemCount - 4) * 110;
        cartForm.style.height = heightForm + "px";
        cartContainer.style.height = heightContainer + "px";
    </script>

{% endblock %}

User/templates/user.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Профіль
{% endblock %}
{% block content %}


    <section class="poster-main-info">
        <div class="container">
            {% for message in messages %}
                <h1> {{ message }}</h1>
            {% endfor %}

            <h1>
                {% if not user.is_superuser %}
                    <a class="user-name" href="{% url 'user:profile' %}">{{ request.user.customer.name }}</a>
                {% else %}
                    <a class="user-name" href="{% url 'user:profile' %}">admin</a>
                {% endif %}
            </h1>
            <hr>
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="block">
                        {% if not user.is_superuser %}
                            <img src="{{ request.user.customer.profile_pic.url }}" alt="">
                        {% else %}
                            <img src="/media/images/default_user.jpg" alt="">
                        {% endif %}
                    </div>
                </div>
                {% if not user.is_superuser %}
                    <div class="col-12 col-lg-6">
                        <div class="full-poster-info">
                            <div class="written-info">
                                <p>Телефон:<br> {{ request.user.customer.phone }}</p>
                            </div>
                            <div class="written-info">
                                <p>Пошта:<br> {{ request.user.customer.email }}</p>
                            </div>
                        </div>
                        <div class="button">
                            <a class="logout-button" href="{% url 'user:profile_change' %}">Редагувати дані</a>
                        </div>
                    </div>
                {% else %}
                    <div class="col-12 col-lg-6">
                        <div class="button">
                                <a class="logout-button" href="{% url 'administrator:banusers' %}">Управління юзерами</a>
                            </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>

    <section class="additional-info-block additional-info-block-info-page profile-length">
        <div class="container">
            {% if not user.is_superuser %}
                <div class="user-div">
                    <div class="user-button">
                        <a class="user-adds" href="{% url 'user:history' %}">Історія замовлень</a>
                    </div>
                    <div class="user-button">
                        <a class="user-adds" href="{% url 'user:wishlist' %}">Список бажань</a>
                    </div>
                </div>
            {% endif %}
            <div class="form">
                <a class="logout-button" href="{% url 'account:logout' %}">Вийти</a>
            </div>
        </div>
    </section>

    <div onclick="show('none')" id="bg-form" class="bg-gray"></div>

{% endblock %}

User/templates/user_change.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Профіль
{% endblock %}
{% block content %}


    <section class="poster-main-info edit-profile-page">
        <div class="container">
            {% for message in messages %}
                <h1> {{ message }}</h1>
            {% endfor %}
            <h1>
                <a class="user-name" href="{% url 'user:profile' %}">{{ request.user.customer.name }}</a>
            </h1>
            <hr>
            {% for field_errors in form.errors.values %}
                {% for error in field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="block">
                        <img src="{{ request.user.customer.profile_pic.url }}" alt="">
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <section class="posters-block posters-block-register">
                        <div class="container">
                            <div class="sub-container">
                                <div class="registration edit-profile-form">
                                    <form name="form" method="POST" enctype="multipart/form-data">
                                        <h2>| Введіть дані |</h2>

                                        {% csrf_token %}

                                        <label class="edit-parameter" for="id_name">Ім'я:</label>
                                        <input type="text" id="id_name" name="name" value="{{ form.name.value }}" class="input">

                                        <label class="edit-parameter" for="id_phone">Телефон:</label>
                                        <input type="text" id="id_phone" name="phone" value="{{ form.phone.value }}" class="input">


                                        <label class="edit-parameter" for="id_email">Пошта:</label>
                                        <input type="email" id="id_email" name="email" value="{{ form.email.value }}" class="input">

                                        <label class="edit-parameter" for="id_profile_pic">Фото профілю:</label>
                                        <input type="file" id="id_profile_pic" name="profile_pic" class="input">


                                        <label class="edit-parameter" for="id_delete_photo">Видалити фото профілю</label>
                                        <input class="delete-photo" type="checkbox" name="delete_photo" id="id_delete_photo">

                                        <button type="submit"> Змінити </button>
                                        <a class="additional-buttom" href="{% url 'user:profile' %}"> Повернутися </a>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </section>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

User/templates/wishlist.html
{% extends 'index.html' %}

{% block title %}
    Афіша подій
{% endblock %}

{% block content %}

    <section class="links links-info-page">
        <div class="container">
            <a href="{% url 'main:landing' %}">На головну</a>
            <p>&nbsp|&nbsp</p>
            <a href="{% url 'user:profile' %}">Профіль</a>
        </div>
    </section>

    <section class="posters-block posters-block-container">
        <div class="container">
            <h1>
                Вибране
            </h1>
            <hr>
            <div class="row">
                {% if events %}
                    {% for event in events %}
                        <div class="col-6 col-xl-3">
                            <div class="poster">
                                <a class="name" href="{% url 'events:event' event.id %}">{{ event.name }}</a>
                                <img src="{{ event.image.url }}" alt="">
                                <div class="calendar">
                                    <img src="/media/images/poster/calendar.png" alt="">
                                    <div class="text">
                                        <p>Від {{ event.from_date|date:"m-d" }} </p>
                                        <p>До {{ event.to_date|date:"m-d" }}</p>
                                    </div>
                                </div>
                                <hr class="poster-hr">
                                <p class="price">{{ event.price }} ГРН.</p>
                                <a href="{% url 'events:event' event.id %}">Переглянути</a>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form">
                    </div>
                {% else %}
                    <h1>
                        Вибране порожнє...
                    </h1>
                {% endif %}
            </div>
        <div class="pagination-form">
                      <ul class="pagination">
                            {% if events.has_previous %}
                                <li class="page-item">
                                    <a href="?page=1">&laquo;</a>
                                    <a href="?page={{ events.previous_page_number }}" rel="prev" aria-label="&laquo; Previous">&lsaquo;</a>
                                </li>
                            {% endif %}
                            <div class="current">
                                <p class="current-page">{{ events.number }}</p>
                                <p>/</p>
                                <p>{{ events.paginator.num_pages }}</p>
                            </div>
                            {% if events.has_next %}
                                <li class="page-item">
                                    <a href="?page={{ events.next_page_number }}" rel="next" aria-label="Next &raquo;">&rsaquo;</a>
                                    <a href="?page={{ events.paginator.num_pages }}">&raquo;</a>
                                </li>
                            {% endif %}
                      </ul>
                </div>
        </div>
    </section>

{% endblock %}