Administrator/urls.py
from django.urls import path
from .views import banusers, ban_user, unban_user, notallowed, event_change, event_create, event_delete

app_name = 'administrator'
urlpatterns = [
    path('banusers/', banusers, name='banusers'),
    path('ban-user/<int:user_id>/', ban_user, name='ban_user'),
    path('unban-user/<int:user_id>/', unban_user, name='unban_user'),
    path('notallowed/', notallowed, name='notallowed'),
    path('event-create/', event_create, name='event_create'),
    path('<int:parameter>/event-change/', event_change, name='event_change'),
    path('<int:parameter>/delete/', event_delete, name='even_delete'),
]

Events/urls.py
from django.urls import path
from .views import all_events, event, favourite_event

app_name = 'events'
urlpatterns = [
    path('', all_events, name='all_events'),
    path('<int:parameter>/', event, name='event'),
    path('<int:parameter>/favourite_event', favourite_event, name='favourite_event'),
]

Main/urls.py
from django.urls import path
from .views import main, about_us, contacts

app_name = 'main'
urlpatterns = [
    path('', main, name='landing'),
    path('aboutus/', about_us, name='about_us'),
    path('contacts/', contacts, name='contacts'),

]

Planetarium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_control
from django.contrib.staticfiles.views import serve
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('', include('Administrator.urls')),
    path('events/', include('Events.urls')),
    path('news/', include('News.urls')),
    path('user/', include('User.urls')),
    path('', include('Account.urls')),
    path('', include('Order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

Events/models.py
from django.db import models

from django.contrib.auth.models import User


class Hall(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name}"


class Event(models.Model):
    name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/events/', default="images/default.png", blank=True)
    from_date = models.DateField()
    to_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    about = models.TextField(max_length=2000)
    hall_id = models.ForeignKey(Hall, on_delete=models.CASCADE, related_name='events')
    popularity = models.PositiveSmallIntegerField()
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

    def __str__(self):
        return f"{self.name}"

Events/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Event
from django.db.models import Q
from django.core.paginator import Paginator
from Administrator.decorators import allowed_users


def all_events(request):

    search_query = request.GET.get('search', '')
    date_picker = request.GET.get('date', '')
    hall_picker = request.GET.getlist('hall', '')
    sorting = request.GET.get('sorting', '')

    if search_query is not None and search_query != ' ':
        events = Event.objects.filter(name__icontains=search_query)
    else:
        events = Event.objects.all()

    if date_picker:
        events = events.filter(from_date__lte=date_picker, to_date__gte=date_picker)

    if hall_picker:
        filters = Q()
        for parameter in hall_picker:
            filters |= Q(hall_id=parameter)
        events = events.filter(filters)

    if sorting:
        events = events.order_by(sorting)

    paginator = Paginator(events, 8)

    page_number = request.GET.get('page')
    paginator_events = paginator.get_page(page_number)
    return render(request, "all_events.html", context={'events': paginator_events})


def event(request, parameter):
    event = Event.objects.get(id=parameter)
    is_favourite = False
    if event.favourite.filter(id=request.user.id).exists():
        is_favourite = True
    return render(request, "event.html", context={'event': event, "is_favourite": is_favourite})


@allowed_users(allowed_roles=['customer'])
@login_required(login_url='account:login')
def favourite_event(request, parameter):
    event = Event.objects.get(id=parameter)
    if event.favourite.filter(id=request.user.id).exists():
        event.favourite.remove(request.user)
    else:
        event.favourite.add(request.user)
    return redirect('events:event', parameter=parameter)

Events/templates/all_events.html
{% extends 'index.html' %}

{% block title %}
    Афіша подій
{% endblock %}

{% block content %}

<section class="links">
    <div class="container">
        <a href="{% url 'main:landing' %}">На головну</a>
        <p>&nbsp|&nbsp</p>
        <a href="{% url 'events:all_events' %}">Афіша</a>
    </div>
</section>


<section class="choice-maker">
        <div class="container">
            <div class="admin-events">
                <h1>
                    Афіша подій
                </h1>
                {% if user.is_superuser %}
                    <a href="{% url 'administrator:event_create' %}">Додати подію</a>
                {% endif %}
            </div>
            <hr>
            <form class="search-form"  method="GET" action="{% url 'events:all_events' %}">
                <div class="row">
                        <div class="col-8 col-lg-3 sorting-boxes">
                            <input  class="search-input" type="date" placeholder="Дата" aria-label="Дата"
                                    name="date">
                        </div>
                        <div class="col-4 col-lg-3 sorting-boxes">
                                <input class="search-input" type="search" placeholder="Пошук" aria-label="Пошук"
                                       name="search">
                        </div>
                        <div class="col-12 col-lg-3 box-form">
                            <div class="check-boxes">
                                <label>
                                    Мала зала
                                    <input type="checkbox" name="hall" value="1">
                                </label>
                            </div>
                            <div class="check-boxes">
                                <label>
                                    Велика зала
                                    <input type="checkbox" name="hall" value="2">
                                </label>
                            </div>
                            <div class="check-boxes">
                                <label>
                                    Зоряна зала
                                    <input type="checkbox" name="hall" value="3">
                                </label>
                            </div>
                        </div>
                        <div class="col-12 col-lg-3 sorting-boxes">
                            <label>
                                <select name="sorting" id="sort-list" class="choicebox order">
                                        <option value="" id="placeholder" disabled selected hidden>Сортування</option>
                                        <option value="name" id="name">Від А до Я</option>
                                        <option value="-name" id="-name">Від Я до А</option>
                                        <option value="price" id="price">Найдешевші</option>
                                        <option value="-price" id="-price">Найдорожчі</option>
                                        <option value="-popularity" id="-popularity">Найпопулярніші</option>
                                        <option value="popularity" id="popularity">Найнепопулярніші</option>
                                </select>
                            </label>
                        </div>
                        <div class="form">
                            <button type="submit" class="search">Пошук</button>
                        </div>
                </div>
            </form>
        </div>
    </section>

<section class="posters-block posters-block-container">
    <div class="container">
        <div class="row">
            {% if events %}
                {% for event in events %}
                    <div class="col-6 col-xl-3">
                        <div class="poster">
                            <a class="name" href="{% url 'events:event' event.id %}">{{ event.name }}</a>
                            <img src="{{ event.image.url }}" alt="">
                            <div class="calendar">
                                <img src="/media/images/poster/calendar.png" alt="">
                                <div class="text">
                                    <p>Від {{ event.from_date|date:"d-m" }} </p>
                                    <p>До {{ event.to_date|date:"d-m" }}</p>
                                </div>
                            </div>
                            <hr class="poster-hr">
                            <p class="price">{{ event.price }} ГРН.</p>
                            <a href="{% url 'events:event' event.id %}">Переглянути</a>
                        </div>
                    </div>
                {% endfor %}


            {% else %}
                <h1>
                    На жаль, подій нема...
                </h1>
            {% endif %}
        </div>

{% load custom_filters %}

<div class="pagination-form">
    <ul class="pagination">
        {% if events.has_previous %}
            <li class="page-item">
                <a href="?page=1{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.date %}&date={{ request.GET.date }}{% endif %}{% for hall in request.GET|getlist_filter:'hall'  %}&hall={{ hall }}{% endfor %}{% if request.GET.sorting %}&sorting={{ request.GET.sorting }}{% endif %}">&laquo;</a>
                <a href="?page={{ events.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.date %}&date={{ request.GET.date }}{% endif %}{% for hall in request.GET|getlist_filter:'hall'  %}&hall={{ hall }}{% endfor %}{% if request.GET.sorting %}&sorting={{ request.GET.sorting }}{% endif %}" rel="prev" aria-label="&laquo; Previous">&lsaquo;</a>
            </li>
        {% endif %}
        <div class="current">
            <p class="current-page">{{ events.number }}</p>
            <p>/</p>
            <p>{{ events.paginator.num_pages }}</p>
        </div>
        {% if events.has_next %}
            <li class="page-item">
                <a href="?page={{ events.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.date %}&date={{ request.GET.date }}{% endif %}{% for hall in request.GET|getlist_filter:'hall'  %}&hall={{ hall }}{% endfor %}{% if request.GET.sorting %}&sorting={{ request.GET.sorting }}{% endif %}" rel="next" aria-label="Next &raquo;">&rsaquo;</a>
                <a href="?page={{ events.paginator.num_pages }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}{% if request.GET.date %}&date={{ request.GET.date }}{% endif %}{% for hall in request.GET|getlist_filter:'hall'  %}&hall={{ hall }}{% endfor %}{% if request.GET.sorting %}&sorting={{ request.GET.sorting }}{% endif %}">&raquo;</a>
            </li>
        {% endif %}
    </ul>
</div>
    </div>
</section>



{% endblock %}

Events/templates/event.html
{% extends 'index.html' %}

{% block title %}
    {{ event.name }}
{% endblock %}

{% block content %}

{% if event %}
    <section class="links links-info-page">
        <div class="container">
            <a href="{% url 'main:landing' %}">На головну</a>
            <p>&nbsp|&nbsp</p>
            <a href="{% url 'events:all_events' %}">Афіша</a>
            <p class="full-name">&nbsp|&nbsp</p>
            <a class="full-name" href="">{{ event.name }}</a>
            <p class="short-name">&nbsp|&nbsp</p>
            <a class="short-name" href="">{{ event.short_name }}</a>
        </div>
    </section>

    <section class="poster-main-info">
        <div class="container">
            <div class="event-upper">
                <h1>
                    {{ event.name }}
                </h1>
                {% if user.is_authenticated and not user.is_superuser %}
                    {% if is_favourite %}
                        <a href="{% url 'events:favourite_event' event.id %}">
                            <i class="fa-solid fa-heart fa-lg" style="color: #ffffff;"></i>
                        </a>
                    {% else %}
                        <a href="{% url 'events:favourite_event' event.id %}">
                            <i class="fa-regular fa-heart fa-lg" style="color: #ffffff;"></i>
                        </a>
                    {% endif %}
                {% endif %}
            </div>
            <hr>
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="block">
                        <img src="{{ event.image.url }}" alt="">
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <div class="full-poster-info">
                        <div class="written-info">
                            <img src="/media/images/poster/calendar.png" alt="">
                            <p>Дата проведення:&nbsp <br> Від {{ event.from_date|date:"d-m-Y" }} -
                                До {{ event.to_date|date:"d-m-Y" }}</p>
                        </div>
                        <div class="written-info">
                            <img src="/media/images/poster/theater.png" alt="">
                            {% if event.hall_id %}
                                <p>{{ event.hall_id.name }}</p>
                            {% else %}
                                <p>Нема зали</p>
                            {% endif %}
                        </div>
                        <div class="written-info">
                            <img src="/media/images/poster/banknotes.png" alt="">
                            <p>Ціна:</p>
                            <p class="price">{{ event.price }} ГРН.</p>
                        </div>
                        {% if user.is_superuser %}
                            <a class="admin-event-change" href="{% url 'administrator:event_change' event.id %}">Змінити</a>
                            <p></p>
                            <a class="admin-event-change" href="{% url 'administrator:even_delete' event.id %}">Видалити</a>
                        {% endif %}
                        {% if not user.is_superuser %}
                            <div class="date-errors" id="error-message" style="color: white;"></div>
                            <div class="written-info">
                                <label for="event-date-input">
                                         Оберіть дату на яку хочете придбати квиток
                                </label>
                            </div>
                            <input name="event_date" type="date" class="input submit-input part-input-date" id="event-date-input" placeholder="Date">
                        </div>
                        <div class="button">
                            <button id="form-button" data-event="{{ event.id }}" data-event_date="" data-action="add">Придбати квиток</button>
                        </div>
                        <div class="button hidden">
                            <button data-event="{{ event.id }}" data-event_date="" data-action="add" class="update-cart"></button>
                        </div>
                        {% endif %}
                </div>
            </div>
        </div>
    </section>

    <section class="additional-info-block additional-info-block-info-page">
        <div class="container">
            <h1>
                Про подію
            </h1>
            <hr>
            <div class="block">
                <div class="spacing">
                    <p>
                        {{ event.about }}
                    </p>
                </div>
            </div>
        </div>
    </section>


{% else %}
    <div class="container">
        <h1>
            На жаль, нема події...
        </h1>
    </div>
{% endif %}

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var formButton = document.getElementById('form-button');
    var eventDateInput = document.getElementById('event-date-input');
    var updateCartButton = document.querySelector('.update-cart');
    var fromDateString = '{{ event.from_date|date:"Y-m-d" }}';
    var toDateString = '{{ event.to_date|date:"Y-m-d" }}';
    var fromDate = new Date(fromDateString);
    var toDate = new Date(toDateString);
    var errorMessage = document.getElementById('error-message');

    formButton.addEventListener('click', function(event) {
      event.preventDefault();
      errorMessage.textContent = '';

      var eventDate = eventDateInput.value;

      if (!eventDate) {
        errorMessage.textContent = 'Ви не обрали дату';
        return NaN;
      }

      var selectedDate = new Date(eventDate);

      if (selectedDate < fromDate || selectedDate > toDate) {
        errorMessage.textContent = 'На цей день квитків немає';
        return NaN;
      }
      else {
          updateCartButton.dataset.event_date = eventDateInput.value;
          updateCartButton.click();
      }

    });
  });
</script>

{% endblock %}