Events/urls.py
from django.urls import path
from .views import all_events, event, favourite_event

app_name = 'events'
urlpatterns = [
    path('', all_events, name='all_events'),
    path('<int:parameter>/', event, name='event'),
    path('<int:parameter>/favourite_event', favourite_event, name='favourite_event'),
]

Main/urls.py
from django.urls import path
from .views import main, about_us, contacts

app_name = 'main'
urlpatterns = [
    path('', main, name='landing'),
    path('aboutus/', about_us, name='about_us'),
    path('contacts/', contacts, name='contacts'),

]

News/urls.py
from django.urls import path
from .views import all_news

app_name = 'news'
urlpatterns = [
    path('', all_news, name='all_news'),
]

Order/urls.py
from django.urls import path
from .views import cart, updateItem, submit, procesOrder

app_name = 'order'
urlpatterns = [
    path('cart/', cart, name='cart'),
    path('submit/', submit, name='submit'),
    path('update_item/', updateItem, name='update_item'),
    path('proces_order/', procesOrder, name='proces_order')
]

Planetarium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_control
from django.contrib.staticfiles.views import serve
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('', include('Administrator.urls')),
    path('events/', include('Events.urls')),
    path('news/', include('News.urls')),
    path('user/', include('User.urls')),
    path('', include('Account.urls')),
    path('', include('Order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

User/urls.py
from django.urls import path
from .views import user, history, order_info, wishlist, user_change

app_name = 'user'
urlpatterns = [
    path('', user, name='profile'),
    path('change/', user_change, name='profile_change'),
    path('history/', history, name='history'),
    path('history/<int:parameter>/', order_info, name='order_info'),
    path('wishlist/', wishlist, name='wishlist')
]

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="/media/images/logo/focus.png">
    <link rel="stylesheet" href={% static "bootstrap-grid.min.css" %}>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Podkova&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "/style.css" %}"  />
{#   <link rel="stylesheet" type="text/css" href="{% static "/style.css" %}?v=1"/>#}
    <script src="https://kit.fontawesome.com/a165d9a4c1.js" crossorigin="anonymous"></script>
    <script src={% static "js/cart.js" %}></script>
    <script type="text/javascript">
        var user = '{{ request.user }}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');


        function getCookie(name) {
            let cookieArr = document.cookie.split(";");

            for(let i = 0; i < cookieArr.length; i++) {
                let cookiePair = cookieArr[i].split("=");

                if(name === cookiePair[0].trim()) {
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            return null
        }

        let cart = JSON.parse(getCookie('cart'));

        if(cart == undefined) {
            cart = {}
            console.log('Cart was created!')
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }

        console.log("Cart: ", cart)

    </script>

    <title>
    {% block title %}
    {% endblock %}
    </title>

</head>

<body>
<header class="header{% if not request.path == '/' %} header-other-pages{% endif %}">
    <hr class="first-line">
    <div class="container">
        <a class="landing-href" href="{% url 'main:landing' %}">
            <div class="logo logo-header">
                <img src="/media/images/logo/focus.png" alt="">
                <div class="name">
                    <p>Planetium</p>
                    <hr>
                    <p>Планетарій</p>
                </div>
            </div>
        </a>
        <div class="menu">
            <a class="menu-item" href="{% url 'events:all_events' %}">Афіша</a>
            <a class="menu-item" href="{% url 'news:all_news' %}">Новини</a>
            <a class="menu-item" href="{% url 'main:about_us' %}">Про планетарій</a>
            <a class="menu-item" href="{% url 'main:contacts' %}">Контакти</a>
        </div>

        <div class="contacts">
            {% if user.is_authenticated %}
                <div class="login">
                    <a href="{% url 'account:logout' %}">Вийти</a>
                </div>
                <div class="login">
                    <a href="{% url 'user:profile' %}">{{ request.user }}</a>
                </div>
            {% else %}
                <div class="login">
                    <a href="{% url 'account:login' %}">Увійти</a>
                </div>
            {% endif %}

            <a href="{% url 'order:cart' %}">
                <img class="profile-pic" src="/media/images/logo/cart.png" alt="">
            </a>

        </div>

        <div class="menu-icon">
            <img src="/media/images/menu/menu.png" alt="">
        </div>
    </div>
    <hr>
</header>

{% block content %}

{% endblock %}


<footer class="footer">
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-8 col-md-6">
                <div class="phone phone-footer">
                    <div class="small">
                        <div>098</div>
                        <div>044</div>
                    </div>
                    456-12-30
                </div>
                <div class="text">
                    <div class="line line-one">
                        <p>Зворотній зв’язок:&nbsp</p>
                        <p>planetium_kyiv@gmail.com</p>
                    </div>
                    <div class="line line-two">
                        <p>Адреса:&nbsp</p>
                        <p>вул. Політехнічна 6, Київ</p>
                    </div>
                    <div class="line line-three">
                        <p>© 2022 Planetaruim “Planetium”.&nbsp</p>
                        <p>All right reserved.</p>
                    </div>
                </div>
            </div>
            <div class="col-4 col-md-6">
                <a class="landing-href" href="{% url 'main:landing' %}">
                    <div class="logo logo-footer">
                        <img src="/media/images/logo/focus.png" alt="">
                        <div class="name ">
                            <p>Planetuim</p>
                            <hr>
                            <p>Планетарій</p>
                        </div>
                    </div>
                </a>
                <div class="media">
                    <a class="media-icon youtube" href="https://www.youtube.com/">
                        <img src="/media/images/media/youtube.png" alt="youtube">
                    </a>
                    <a class="media-icon instagram" href="https://www.instagram.com/">
                        <img src="/media/images/media/instagram.png" alt="">
                    </a>
                    <a class="media-icon facebook" href="https://www.facebook.com/">
                        <img src="/media/images/media/facebook.png" alt="">
                    </a>
                </div>
            </div>
        </div>
    </div>
    <hr class="last-line">
</footer>
</body>
</html>